### ISSUE TITLE
How should i use this?

### ISSUE THREAD

**Issue by Stay1444** [Cryptkeeper/mcping-js#3]
Sorry for bothering you... Im new to this thing of websites and im making a simple website to a comunity. If i place this in the script it works or it functions server side? If its server side, how would i do it? Sorry for bothering you x2. Im using netlify if that helps with something.
Thanks.

**Comment by Cryptkeeper** [comment]
It runs within a Javascript runtime like [nodejs](https://nodejs.org/en/) (so in this case, "server side" vs the browser). I'm not familiar with Netlify, but it seems like they do not offer this functionality currently.
