### ISSUE TITLE
Socket Timeout for servers that are online

### ISSUE THREAD

**Issue by alex-r89** [Cryptkeeper/mcping-js#6]
Hi,

I am getting Socket timeout errors for servers that are definitely online. I have tried longer timeouts (500 to 5000 ms), as well as multiple different protocol versions - neither of these fixes the issue.

An example servers is `play.minewind.com`. Hitting this server via an api like mcsrvstat returns the correct data:
https://mcsrvstat.us/server/play.minewind.com

**Comment by Cryptkeeper** [comment]
`mcping-js` does not support SRV records directly. You'll need to explicitly resolve the SRV record like so: https://github.com/Cryptkeeper/Minetrack/blob/master/lib/dns.js#L49
